# Generated by Django 4.2.3 on 2023-07-05 12:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('map', models.CharField(default='N/A', max_length=50)),
                ('map_size', models.CharField(default='N/A', max_length=50)),
                ('game_mode', models.CharField(default='N/A', max_length=50)),
                ('region', models.CharField(default='N/A', max_length=100)),
                ('players', models.IntegerField(default=0)),
                ('queue_players', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=0)),
                ('hz', models.IntegerField(default=0)),
                ('day_night', models.CharField(default='N/A', max_length=50)),
                ('is_official', models.BooleanField(default=False)),
                ('has_password', models.BooleanField(default=False)),
                ('anti_cheat', models.CharField(default='N/A', max_length=50)),
                ('build', models.CharField(default='N/A', max_length=50)),
            ],
            options={
                'verbose_name': 'Server Statistic',
                'verbose_name_plural': 'Server Statistics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at', 'batch_id'], name='name_date_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('batch_id', 'timestamp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MapStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('batch_id', 'timestamp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MapSizeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('batch_id', 'timestamp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GameModeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('batch_id', 'timestamp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DayNightStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('total_players', models.IntegerField(default=0)),
                ('total_servers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('batch_id', 'timestamp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AggregatedServerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_players', models.IntegerField(default=0)),
                ('total_maps', models.IntegerField(default=0)),
                ('total_regions', models.IntegerField(default=0)),
                ('total_map_sizes', models.IntegerField(default=0)),
                ('most_used_map', models.CharField(max_length=100)),
                ('most_used_map_count', models.IntegerField(default=0)),
                ('most_used_map_total_players', models.IntegerField(default=0)),
                ('least_used_map', models.CharField(max_length=100)),
                ('least_used_map_count', models.IntegerField(default=0)),
                ('least_used_map_total_players', models.IntegerField(default=0)),
                ('most_used_map_size', models.CharField(max_length=100)),
                ('most_used_map_size_count', models.IntegerField(default=0)),
                ('most_used_map_size_total_players', models.IntegerField(default=0)),
                ('least_used_map_size', models.CharField(max_length=100)),
                ('least_used_map_size_count', models.IntegerField(default=0)),
                ('least_used_map_size_total_players', models.IntegerField(default=0)),
                ('most_used_game_mode', models.CharField(max_length=100)),
                ('most_used_game_mode_count', models.IntegerField(default=0)),
                ('most_used_game_mode_total_players', models.IntegerField(default=0)),
                ('least_used_game_mode', models.CharField(max_length=100)),
                ('least_used_game_mode_count', models.IntegerField(default=0)),
                ('least_used_game_mode_total_players', models.IntegerField(default=0)),
                ('most_used_region', models.CharField(max_length=100)),
                ('most_used_region_count', models.IntegerField(default=0)),
                ('most_used_region_total_players', models.IntegerField(default=0)),
                ('least_used_region', models.CharField(max_length=100)),
                ('least_used_region_count', models.IntegerField(default=0)),
                ('least_used_region_total_players', models.IntegerField(default=0)),
                ('most_common_time_of_day', models.CharField(max_length=50)),
                ('most_common_time_of_day_count', models.IntegerField(default=0)),
                ('most_common_time_of_day_total_players', models.IntegerField(default=0)),
                ('least_common_time_of_day', models.CharField(max_length=50)),
                ('least_common_time_of_day_count', models.IntegerField(default=0)),
                ('least_common_time_of_day_total_players', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('batch_id', 'timestamp')},
            },
        ),
    ]
