# Generated by Django 4.2.3 on 2023-07-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daynightaggstatistics',
            old_name='day_night',
            new_name='day_night_name',
        ),
        migrations.RenameField(
            model_name='mapsizeaggstatistics',
            old_name='map_size',
            new_name='map_size_name',
        ),
    ]
