# Generated by Django 4.2.3 on 2023-07-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0002_alter_daynightstatistics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynightstatistics',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='gamemodestatistics',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='mapsizestatistics',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='mapstatistics',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='regionstatistics',
            options={'ordering': ['timestamp']},
        ),
    ]
