# Generated by Django 4.2.3 on 2023-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0003_alter_daynightstatistics_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('date', 'region')},
            },
        ),
    ]
