# Generated by Django 4.2.3 on 2023-07-03 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0004_serverstatistics_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModeAggStatistics',
            fields=[
                ('game_mode_name', models.CharField(default='N/A', max_length=50, primary_key=True, serialize=False)),
                ('average_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('min_players', models.IntegerField(default=0)),
                ('most_used_map', models.CharField(default='N/A', max_length=50)),
                ('most_used_region', models.CharField(default='N/A', max_length=100)),
                ('most_used_server', models.CharField(default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Game Mode Aggregate Statistic',
                'verbose_name_plural': 'Game Mode Aggregate Statistics',
            },
        ),
        migrations.CreateModel(
            name='MapAggStatistics',
            fields=[
                ('map_name', models.CharField(default='N/A', max_length=50, primary_key=True, serialize=False)),
                ('average_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('min_players', models.IntegerField(default=0)),
                ('most_used_game_mode', models.CharField(default='N/A', max_length=50)),
                ('most_used_region', models.CharField(default='N/A', max_length=100)),
                ('most_used_server', models.CharField(default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Map Aggregate Statistic',
                'verbose_name_plural': 'Map Aggregate Statistics',
            },
        ),
        migrations.CreateModel(
            name='RegionAggStatistics',
            fields=[
                ('region_name', models.CharField(default='N/A', max_length=100, primary_key=True, serialize=False)),
                ('average_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('min_players', models.IntegerField(default=0)),
                ('most_used_map', models.CharField(default='N/A', max_length=50)),
                ('most_used_game_mode', models.CharField(default='N/A', max_length=50)),
                ('most_used_server', models.CharField(default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Region Aggregate Statistic',
                'verbose_name_plural': 'Region Aggregate Statistics',
            },
        ),
        migrations.CreateModel(
            name='ServerAggStatistics',
            fields=[
                ('server_name', models.CharField(default='N/A', max_length=100, primary_key=True, serialize=False)),
                ('average_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('min_players', models.IntegerField(default=0)),
                ('most_used_map', models.CharField(default='N/A', max_length=50)),
                ('most_used_game_mode', models.CharField(default='N/A', max_length=50)),
                ('most_used_region', models.CharField(default='N/A', max_length=100)),
                ('is_official', models.BooleanField(default=False)),
                ('has_password', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Server Aggregate Statistic',
                'verbose_name_plural': 'Server Aggregate Statistics',
            },
        ),
        migrations.CreateModel(
            name='TimeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('average_players', models.FloatField(default=0.0)),
                ('max_players', models.IntegerField(default=0)),
                ('min_players', models.IntegerField(default=0)),
                ('most_used_map', models.CharField(default='N/A', max_length=50)),
                ('most_used_game_mode', models.CharField(default='N/A', max_length=50)),
                ('most_used_region', models.CharField(default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Time Statistic',
                'verbose_name_plural': 'Time Statistics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='serverstatistics',
            options={'ordering': ['-created_at'], 'verbose_name': 'Server Statistic', 'verbose_name_plural': 'Server Statistics'},
        ),
        migrations.AddIndex(
            model_name='serverstatistics',
            index=models.Index(fields=['name', 'created_at'], name='name_date_idx'),
        ),
        migrations.AddIndex(
            model_name='timestatistics',
            index=models.Index(fields=['timestamp'], name='timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='serveraggstatistics',
            index=models.Index(fields=['server_name'], name='server_name_idx'),
        ),
        migrations.AddIndex(
            model_name='regionaggstatistics',
            index=models.Index(fields=['region_name'], name='region_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mapaggstatistics',
            index=models.Index(fields=['map_name'], name='map_name_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemodeaggstatistics',
            index=models.Index(fields=['game_mode_name'], name='game_mode_name_idx'),
        ),
    ]
