# Generated by Django 4.2.3 on 2023-07-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0005_gamemodeaggstatistics_mapaggstatistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestatistics',
            name='period',
            field=models.CharField(choices=[('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_7_days', 'Last 7 Days')], default='last_day', max_length=20),
        ),
    ]
