# Generated by Django 4.2.3 on 2023-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0006_timestatistics_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatistics',
            name='total_players',
            field=models.IntegerField(default=0),
        ),
    ]
