# Generated by Django 4.2.3 on 2023-07-03 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battlebit', '0008_rename_average_players_gamemodeaggstatistics_total_average_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodeaggstatistics',
            name='period',
            field=models.CharField(choices=[('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_7_days', 'Last 7 Days')], default='last_day', max_length=20),
        ),
        migrations.AddField(
            model_name='gamemodeaggstatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mapaggstatistics',
            name='period',
            field=models.CharField(choices=[('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_7_days', 'Last 7 Days')], default='last_day', max_length=20),
        ),
        migrations.AddField(
            model_name='mapaggstatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='regionaggstatistics',
            name='period',
            field=models.CharField(choices=[('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_7_days', 'Last 7 Days')], default='last_day', max_length=20),
        ),
        migrations.AddField(
            model_name='regionaggstatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serveraggstatistics',
            name='period',
            field=models.CharField(choices=[('last_hour', 'Last Hour'), ('last_day', 'Last Day'), ('last_7_days', 'Last 7 Days')], default='last_day', max_length=20),
        ),
        migrations.AddField(
            model_name='serveraggstatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
